name: youtube_explode_dart
description: A port in dart of the youtube explode library. Supports several API functions without the need of Youtube API Key.
version: 1.11.0

homepage: https://github.com/Hexer10/youtube_explode_dart

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  freezed_annotation: ^2.0.3
  html: ^0.15.0
  http: ^0.13.4
  http_parser: ^4.0.0
  json_annotation: ^4.6.0
  meta: ^1.7.0
  xml: ^5.3.1

dev_dependencies:
  build_runner: ^2.1.11
  console: ^4.1.0
  freezed: ^2.0.4
  json_serializable: ^6.3.1
  lint: ^1.8.1
  test: ^1.19.5

false_secrets:
  - "lib/src/reverse_engineering/youtube_http_client.dart"
  - "lib/src/reverse_engineering/clients/embedded_player_client.dart"
