name: youtube_explode_dart
description: A port in dart of the youtube explode library. Supports several API functions without the need of Youtube API Key.
version: 1.12.0

homepage: https://github.com/Hexer10/youtube_explode_dart

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  freezed_annotation:
  html: ^0.15.0
  http: ^0.13.4
  http_parser: ^4.0.0
  json_annotation:
  meta: ^1.7.0
  xml: ^5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  console: ^4.1.0
  build_runner: ^2.1.11
  freezed:
  json_serializable:
  lint: ^1.8.2

false_secrets:
  - "lib/src/reverse_engineering/youtube_http_client.dart"
  - "lib/src/reverse_engineering/clients/embedded_player_client.dart"
