name: youtube_explode_dart
description: A port in dart of the youtube explode library. Supports several API functions without the need of Youtube API Key.
version: 1.12.1

homepage: ^0.13.5

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  freezed_annotation: ^2.2.0
  html: ^0.15.1
  http: ^0.13.4
  http_parser: ^4.0.2
  json_annotation:
  meta: ^1.8.0
  xml: ^6.2.2

dev_dependencies:
  console: ^4.1.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable:
  lint: ^2.0.1

false_secrets:
  - "lib/src/reverse_engineering/youtube_http_client.dart"
  - "lib/src/reverse_engineering/clients/embedded_player_client.dart"
